#include "stm32f0xx_hal.h"
#include <sys/unistd.h>
#include <stdio.h>

/* External declaration of the UART handle for USART2.
   This handle is typically defined in the file generated by CubeMX (e.g., usart.c). */
extern UART_HandleTypeDef huart2;

/**
 * @brief  Retargets the C library printf function to USART2.
 * @param  file: File handle (not used).
 * @param  ptr: Pointer to the buffer containing the data to be transmitted.
 * @param  len: Length of the data.
 * @return The number of characters transmitted.
 */
int _write(int file, char *ptr, int len)
{
    /* Transmit data via USART2 */
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}
